### ISSUE TITLE
art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ....handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)

### ISSUE THREAD

**Issue by 3c71** [rovo89/android_art#72]
I built an Xposed module since a few years, and users are now reporting a weird issue in which the app itself no longer starts when its integrated module is enabled.

When module is enabled, the Xposed logs shows many lines like this:

art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)

Not sure what it means or if it relates to the app no longer starting, but it's odd enough as the method in question is quite simple:

	@Override
	public void handleLoadPackage(LoadPackageParam lpparam) throws Throwable
	{
		String self = at_xposed_helpers.getPackageName();

		if (lpparam.packageName.equals(self))
		{
			findAndHookMethod("ccc71.at.xposed.at_xposed_helpers", lpparam.classLoader, "isXposedEnabled", new XC_MethodHook()
			{
				@Override
				protected void beforeHookedMethod(MethodHookParam param) throws Throwable
				{
					param.setResult(at_xposed_helpers.VERSION);
				}
			});
		}
	}
	
	static String getPackageName()
	{
        return BuildConfig.XPOSED_PACKAGE;
	}

Can anybody help me understand how an Xposed module being enabled would prevent the hosting app from starting? There's nothing in logcat, no ANR nor any tombstones when this happens. Just those lines in the log attached.

[xposed_error_20171206_062700.log](https://github.com/rovo89/android_art/files/1536926/xposed_error_20171206_062700.log)

**Comment by rovo89** [comment]
This is probably one of the issues mentioned here: https://github.com/rovo89/android_art/issues/72
Please see my latest reply in that issue.

**Comment by wanam** [comment]
@rovo89 you mean here https://github.com/rovo89/Xposed/issues/275

**Comment by rovo89** [comment]
These crashes should be fixed with v89 which I released last night.

**Comment by ElminsterAU** [comment]
I'm still seeing this issue with v89.

C3 Toolbox is not running after boot and doesn't start when selected in the launcher.

Xposed log is full of:

12-19 08:59:38.752 F/art     ( 3972): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:00:00.485 F/art     ( 4926): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:01:32.055 F/art     ( 5919): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:04:54.503 F/art     ( 9789): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
....

See my comments in issue rovo89/Xposed#275 for additional information.

**Comment by 3c71** [comment]
Sorry to hear that.


I’m running v89 on top of Magisk and have no issues so far.

 

Are you sure v89 is loaded? Have you tried the ‘fix’ referred in rovio threads:

 

cmd package compile --reset ccc71.at

 

Many users have reported it fixes the issue, however it might only be temporary?

 

It might be permanent if the issue comes from ‘old’ cache still providing old code somehow.

 

3C.

 

De : eFrysTon [mailto:notifications@github.com] 
Envoyé : mardi 19 décembre 2017 01:32
À : rovo89/android_art <android_art@noreply.github.com>
Cc : 3c71 <ccounotte@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [rovo89/android_art] art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ....handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam) (#72)

 

I'm still seeing this issue with v89.

C3 Toolbox is not running after boot and doesn't start when selected in the launcher.

Xposed log is full of:

12-19 08:59:38.752 F/art ( 3972): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:00:00.485 F/art ( 4926): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:01:32.055 F/art ( 5919): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
12-19 09:04:54.503 F/art ( 9789): art/runtime/stack.cc:205] Check failed: success Failed to read the this object in void ccc71.at.xposed.at_xposed_enabled.handleLoadPackage(de.robv.android.xposed.callbacks.XC_LoadPackage$LoadPackageParam)
....

See my comments in issue #275 for additional information.

**Comment by ElminsterAU** [comment]
I'm very sure I'm running v89 correctly.

It's fine right after I boot to system from recovery after wiping dalvik/art cache and cache, but it starts/keeps failing again after some time.

I'm pretty sure it's directly related to the issues caused by BackgroundDexOptService  described in rovo89/Xposed#275

**Comment by rovo89** [comment]
Then I'll have to look at these issues again next year. For now, my focus is on Oreo, especially as the latest fixes seem to work for most people.

I'd just like to mention again that the background dexing and resetting the compiled code is just about the symptoms. Please don't call this a fix.
